[package]
name = "webview_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = {version = "0.40.0", default-features = false}
tao = "0.28.0"